#+TITLE: Michael Tu, Ph.D.
I'm a biomedical engineering researcher who loves working with laboratory automation, diagnostics, and biosensors. For fun I like to cook, read books, and tinker with my [[https://github.com/miketu/.emacs][.emacs file]]. I'm a fan of [[https://github.com/miketu/learn_r][R]] .

* 💼 Experience 
| Date        | Organization             | Role                     |
|-------------|--------------------------|--------------------------|
| 2024 - Now      | Thermo Fisher Scientific | Scientist III  (Automation)          |
| 2020 - 2024 | Liquid Diagnostics LLC   | Principal Scientist      |
| 2017 - 2020 | EZLife Bio Inc           | R&D Director             |
| 2015 - 2017 | UCLA Dentistry           | T90 Postdoctoral Scholar |
| 2012-2015   | UCLA Dentistry           | T32 Predoctoral Scholar  |
| 2011        | Evidia Biosciences       | Consultant               |
| 2009 - 2012 | UCLA Engineering         | Teacher's Assistant      |
| 2008        | Genefluidics             | Intern                   |

* 🎓Education
| Degree | Institution                   | Year |
|--------|-------------------------------|------|
| PhD    | UCLA (Biomedical Engineering) | 2015 |
| MS     | UCLA (Biomedical Engineering) | 2010 |
| BS     | UCLA (Bioengineering)         | 2009 |


* 📑 Select Publications

- ⭐ M. K. Tu, et al. "The Kinetics of COVID-19 Vaccine Response in a Community-Vaccinated Population," J.I., p. ji2100919, Jan. 2022, doi: 10.4049/jimmunol.2100919.

- ⭐ M. Tu et al., "Rapid PCR-Free Meat Species Identification using Electric Field Induced Release and Measurement (EFIRM®)," Analytica Chimica Acta, p. S000326701931414X, Nov. 2019, doi: 10.1016/j.aca.2019.11.051.

- S. H. Chiang, M.Tu, et al., "Development and validation of a quantitative, non-invasive, highly sensitive and specific, electrochemical assay for anti-SARS-CoV-2 IgG antibodies in saliva," PLoS ONE, vol. 16, no. 7, p. e0251342, Jul. 2021, doi: 10.1371/journal.pone.0251342.

- M. Tu et al., "Electric Field Induced Release and Measurement (EFIRM): Characterization and Technical Validation of a Novel Liquid Biopsy Platform in Plasma and Saliva," The Journal of Molecular Diagnostics, p. S1525157820303500, Jun. 2020, doi: 10.1016/j.jmoldx.2020.05.005.

- M. Tu, D. Chia, F. Wei, and D. Wong, "Liquid biopsy for detection of actionable oncogenic mutations in human cancers and electric field induced release and measurement liquid biopsy (eLB)," The Analyst, 2016, doi: 10.1039/C5AN01863C.

- M. Suh et al., "A Remote Patient Monitoring System for Congestive Heart Failure," Journal of Medical Systems, vol. 35, no. 5, pp. 1165--1179, May 2011, doi: 10.1007/s10916-011-9733-y.

- [[https://orcid.org/0000-0002-7227-4030][Full list📚]]
